# Generated by Django 3.0.8 on 2020-07-24 15:36

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200724_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=55, validators=[productos.models.validate_name]),
        ),
    ]
